version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PokeTactician
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USE_IN_MEMORY_DATABASE=False
      - ConnectionStrings__DefaultConnection=Host=db;Database=PokeTactician;Username=postgres;Password=postgres
    depends_on:
      - db

volumes:
  postgres_data:
