version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PokeTactician
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=
        - PAT=${PAT}
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db

volumes:
  postgres_data:
